/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Apli1;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.awt.FileDialog;

import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.media.Buffer;
import javax.media.CannotRealizeException;
import javax.media.Manager;
import javax.media.MediaLocator;
import javax.media.NoPlayerException;
import javax.media.Player;
import javax.media.control.FrameGrabbingControl;
import javax.media.format.VideoFormat;
import javax.media.util.BufferToImage;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import JImage.JIResizeImage;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import static org.hibernate.criterion.Expression.sql;

import static sun.audio.AudioPlayer.player;
import java.awt.image.BufferedImage;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.highgui.VideoCapture;
 import java.sql.*;
 import javax.swing.*;



/**
 *
 * @author Francimar
 */
public class Apli0 extends javax.swing.JFrame {
    ResultSet RS;
    Player player;
    ConectaBanco conecta = new ConectaBanco();
    BufferedImage bi;
    String nfile;


FileInputStream fis;
int longitudBytes;

    /**
     * Creates new form Apli0
     */
    public Apli0() {
        super("SGBD");
        initComponents();
        conecta.conexao();
        try {
            initCamera();
        } 
        catch (IOException ex) 
        {
            Logger.getLogger(Apli0.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (NoPlayerException ex)
        {
            Logger.getLogger(Apli0.class.getName()).log(Level.SEVERE, null, ex);
        } 
        catch (CannotRealizeException ex)
        {
            Logger.getLogger(Apli0.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setIconImage(new ImageIcon(getClass().getResource("/imagens/w10.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("cf0?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        cf3Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cf3 c");
        cf3List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cf3Query.getResultList();
        cf5Query = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT c FROM Cf5 c");
        cf5List = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : cf5Query.getResultList();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        tbCamera = new javax.swing.JToggleButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Matrícula:");

        jLabel2.setText("Nome:");

        jLabel4.setText("Endereço:");

        jLabel5.setText("Telefone:");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("RG:");

        jLabel7.setText("CPF/CNPJ:");

        jLabel8.setText("Observações:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setText("Alterar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 51));
        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 204, 51));
        jButton4.setText("Voltar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 204, 51));
        jButton5.setText("Limpar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 204, 51));
        jButton6.setText("Carregar Foto");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 204, 51));
        jButton7.setText("Relatório");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cf3List, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${matricula}"));
        columnBinding.setColumnName("Matricula");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${endereco}"));
        columnBinding.setColumnName("Endereco");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${telefone}"));
        columnBinding.setColumnName("Telefone");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${rg}"));
        columnBinding.setColumnName("Rg");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cpf}"));
        columnBinding.setColumnName("Cpf");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane2.setViewportView(jTable1);

        tbCamera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbCameraActionPerformed(evt);
            }
        });

        jButton8.setText("Capturar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Salvar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Parar");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Alterar Foto");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel9.setText("Pesquisar Matrícula:");

        jLabel10.setText("Pesquisar Nome:");

        jButton12.setBackground(new java.awt.Color(255, 51, 51));
        jButton12.setText("...");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(new java.awt.Color(255, 51, 51));
        jButton13.setText("...");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(35, 35, 35)
                                .addComponent(jButton2)
                                .addGap(37, 37, 37)
                                .addComponent(jButton3)
                                .addGap(44, 44, 44)
                                .addComponent(jButton4)
                                .addGap(40, 40, 40)
                                .addComponent(jButton5)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(148, 148, 148)
                                        .addComponent(tbCamera, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(173, 173, 173)
                                        .addComponent(jButton8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton11))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jButton6)
                                .addGap(41, 41, 41)
                                .addComponent(jButton7))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton12))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton13)))))
                .addContainerGap(422, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbCamera, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8)
                            .addComponent(jButton9)
                            .addComponent(jButton10)
                            .addComponent(jButton11)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 81, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton13))
                .addGap(0, 242, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Usuários", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Código:");

        jLabel12.setText("Nome:");

        jLabel13.setText("Endereço:");

        jLabel14.setText("Telefone:");

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel15.setText("RG:");

        jLabel16.setText("CPF/CNPJ:");

        jLabel17.setText("Descrição:");

        jLabel18.setText("Valor:");

        jLabel19.setText("Desconto:");

        jLabel20.setText("Valor Total:");

        jLabel21.setText("Observacões:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jButton14.setBackground(new java.awt.Color(0, 204, 51));
        jButton14.setText("Cadastrar");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(0, 204, 51));
        jButton15.setText("Alterar");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(new java.awt.Color(0, 204, 51));
        jButton16.setText("Excluir");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(new java.awt.Color(0, 204, 51));
        jButton17.setText("Limpar");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(0, 204, 51));
        jButton18.setText("Relatório");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cf5List, jTable2);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${codigo}"));
        columnBinding.setColumnName("Codigo");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${nome}"));
        columnBinding.setColumnName("Nome");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${endereco}"));
        columnBinding.setColumnName("Endereco");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${telefone}"));
        columnBinding.setColumnName("Telefone");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${rg}"));
        columnBinding.setColumnName("Rg");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${cpf}"));
        columnBinding.setColumnName("Cpf");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${produto}"));
        columnBinding.setColumnName("Produto");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${valor}"));
        columnBinding.setColumnName("Valor");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${desconto}"));
        columnBinding.setColumnName("Desconto");
        columnBinding.setColumnClass(String.class);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${total}"));
        columnBinding.setColumnName("Total");
        columnBinding.setColumnClass(String.class);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();

        jScrollPane4.setViewportView(jTable2);

        jLabel22.setText("Pesquisar Código:");

        jButton19.setBackground(new java.awt.Color(255, 51, 51));
        jButton19.setText("...");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jLabel23.setText("Pesquisar Nome:");

        jButton20.setBackground(new java.awt.Color(255, 51, 51));
        jButton20.setText("...");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(0, 204, 51));
        jButton21.setText("Carregar Dados");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton22.setBackground(new java.awt.Color(0, 204, 51));
        jButton22.setText("|<<");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jButton23.setBackground(new java.awt.Color(0, 204, 51));
        jButton23.setText("<<");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(0, 204, 51));
        jButton24.setText(">>");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        jButton25.setBackground(new java.awt.Color(0, 204, 51));
        jButton25.setText(">>|");
        jButton25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel19)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextField13, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel15)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(28, 28, 28)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(147, 147, 147)
                                                .addComponent(jButton14)
                                                .addGap(47, 47, 47)
                                                .addComponent(jButton15)
                                                .addGap(161, 161, 161))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton16)
                                                .addGap(44, 44, 44)))
                                        .addComponent(jButton17)
                                        .addGap(46, 46, 46)
                                        .addComponent(jButton18)))
                                .addGap(38, 38, 38)
                                .addComponent(jButton21))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(369, 369, 369)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton19)
                            .addComponent(jButton20)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(566, 566, 566)
                        .addComponent(jButton22)
                        .addGap(18, 18, 18)
                        .addComponent(jButton23)
                        .addGap(18, 18, 18)
                        .addComponent(jButton24)
                        .addGap(18, 18, 18)
                        .addComponent(jButton25)))
                .addContainerGap(385, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton15)
                    .addComponent(jButton14)
                    .addComponent(jButton16)
                    .addComponent(jButton17)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton21)
                        .addComponent(jButton18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton22)
                    .addComponent(jButton23)
                    .addComponent(jButton24)
                    .addComponent(jButton25))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20))
                .addContainerGap(190, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
private void initCamera() throws IOException,NoPlayerException,CannotRealizeException
   {
    MediaLocator ml = new  MediaLocator("vfw://0");
        player = Manager.createRealizedPlayer(ml);
        this.tbCamera.add(player.getVisualComponent());
        this.setVisible(true);
        player.start();
        
       
       
       
       
   }
   
  private void setImageButton(JToggleButton tbutton,Image image) 
  {
   tbutton.setIcon(new ImageIcon(image));
  }


    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
     jButton1.setBackground(Color.RED); 
        if(jTextField1.getText().contains(" ") || jTextField1.getText().equals("")){
       jTextField1.requestFocus();
       JOptionPane.showMessageDialog( null, "Preencha os espaços da Página! ","Aviso",JOptionPane.WARNING_MESSAGE); 
       return;
      }
   try{ //tratamento de erros
         Class.forName("com.mysql.jdbc.Driver");//Driver JDBC – Fonte de Dados ODBC
         String sql = "insert into cf3 (Matricula,Nome,Endereco,Telefone,Rg,CPF,Observacao,Foto) values (?,?,?,?,?,?,?,?)";            
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cf0","root","fss3");
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, Integer.parseInt(jTextField1.getText()));
       ps.setString(2, jTextField2.getText());
           
        ps.setString(3, jTextField3.getText());
        ps.setString(4, jFormattedTextField1.getText());
        ps.setString(5, jTextField4.getText());  
        ps.setString(6, jTextField5.getText());
        ps.setString(7, jTextArea1.getText());
        ps.setBinaryStream(8, fis,longitudBytes);
        JOptionPane.showMessageDialog( this, " Dados Salvos! ");
        ps.execute();
        ps.close();
        con.close();  // fecha conexão com BD
        jLabel3.setIcon(null);
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jFormattedTextField1.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextArea1.setText("");
      }  catch( SQLException e){ //trata os erros SQL
            JOptionPane.showMessageDialog(this, "Erro Cmdo SQL " + e.getMessage() );
            } catch( ClassNotFoundException e){      //trata erros de conexão
             JOptionPane.showMessageDialog( this, " Driver não encontrado " );
            }  
    








    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    jButton2.setBackground(Color.RED); 
        if(jTextField6.getText().contains(" ") || jTextField6.getText().equals("")){
       jTextField6.requestFocus();
       JOptionPane.showMessageDialog( null, "Pesquise uma Matrícula! ","Aviso",JOptionPane.WARNING_MESSAGE); 
       return;
      }    
     try{ //tratamento de erros
      Class.forName("com.mysql.jdbc.Driver");//busca Driver
      //conecta no BD
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cf0","root","fss3");
      Statement stmt= con.createStatement();//objeto comdo sql
String consMatricula= jTextField6.getText();
String cadMat=jTextField1.getText();
String cadNome=jTextField2.getText();
String cadEnd=jTextField3.getText();
String cadTel=jFormattedTextField1.getText();
String cadRG=jTextField4.getText();
String cadCPF=jTextField5.getText();
String cadObs=jTextArea1.getText();

int registro = stmt.executeUpdate("update cf3 set Nome='" + cadNome + "', Matricula='" + cadMat + "',  Endereco='" + cadEnd + "', telefone='" + cadTel + "', RG='" + cadRG + "', CPF='" + cadCPF + "', Observacao='" + cadObs + "' where Matricula=" + consMatricula);   
if (registro!=0) JOptionPane.showMessageDialog(this,"Dados Alterados!");
                 else JOptionPane.showMessageDialog(this,"Dados Não Alterados!");
            stmt.close();
            con.close(); //fecha conexão com BD
      } catch(SQLException e){ //trata os erros
            JOptionPane.showMessageDialog(this,"Erro Cmdo SQL "+e.getMessage());
            } catch(ClassNotFoundException e){       
             JOptionPane.showMessageDialog(this,"Driver não encontrado");
        }
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
     jButton12.setBackground(Color.GREEN); 
        if(jTextField6.getText().contains(" ") || jTextField6.getText().equals("")){
       jTextField6.requestFocus();
       JOptionPane.showMessageDialog( null, "Pesquise uma Matrícula! ","Aviso",JOptionPane.WARNING_MESSAGE); 
       return;
      }    
     boolean consulta=true;  
           
         
          try{ 
            //tratamento de erros
           
           
            //conecta no BD
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cf0","root","fss3");
            Statement stmt= con.createStatement();//objeto comdo sql
           
            ResultSet RS= stmt.executeQuery("Select foto,matricula,nome,endereco,telefone,rg,cpf,observacao from cf3 where Matricula=" + jTextField6.getText() );
             while (RS.next()){
             ImageIcon Foto;
             InputStream is;
             String Matricula; 
             String Nome;
             String Endereco; 
             String Telefone;
             String RG;
             String CPF;
             String Observacao; 
            is = RS.getBinaryStream(1);
            Matricula = RS.getString(2);
            Nome = RS.getString(3);
            Endereco = RS.getString(4);
            Telefone = RS.getString(5);
            RG = RS.getString(6);
            CPF = RS.getString(7);
            Observacao = RS.getString(8);
             BufferedImage bi = ImageIO.read(is);
             Foto = new ImageIcon(bi);
             Image img = Foto.getImage();
             Image newimg = img.getScaledInstance(140, 170, java.awt.Image.SCALE_SMOOTH);
             ImageIcon newicon = new ImageIcon(newimg);
             jLabel3.setIcon(newicon);
             jTextField1.setText(Matricula);
             jTextField2.setText(Nome);
             jTextField3.setText(Endereco);
             jFormattedTextField1.setText(Telefone);
             jTextField4.setText(RG);
             jTextField5.setText(CPF);
             jTextArea1.setText(Observacao);
              consulta=false;
                
             }
            if (consulta) JOptionPane.showMessageDialog(this,"Dados Não Encontrados!");
              
            }  catch( SQLException e){ //trata os erros SQL
            JOptionPane.showMessageDialog(this, "Erro Cmdo SQL " + e.getMessage() ); 
            }  catch( IOException ex){
           JOptionPane.showMessageDialog(rootPane, "exception: " + ex);   
            }
    
   
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
 jButton6.setBackground(Color.RED);  

jLabel3.setIcon(null);
         JFileChooser j = new JFileChooser();
         j.setFileSelectionMode(JFileChooser.FILES_ONLY);
         int estado=j.showOpenDialog(null);
          if (estado== JFileChooser.APPROVE_OPTION){
          try{
              fis=new FileInputStream(j.getSelectedFile());
              this.longitudBytes=(int)j.getSelectedFile().length();
              try{
          Image icone=ImageIO.read(j.getSelectedFile()).getScaledInstance(jLabel3.getWidth(), jLabel3.getHeight(),Image.SCALE_DEFAULT);
          jLabel3.setIcon(new ImageIcon(icone));
           jLabel3.updateUI();
            }  catch( IOException ex){
                 JOptionPane.showMessageDialog(rootPane, "exception: " + ex);
                  }  
           }  catch( FileNotFoundException ex){
           ex.printStackTrace();        
          }
    } 

       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton4.setBackground(Color.RED);  
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       jButton5.setBackground(Color.RED);  
        jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
jFormattedTextField1.setText("");
jTextField4.setText("");
jTextField5.setText("");
jTextArea1.setText("");
jLabel3.setIcon(null);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
      
        if(jTextField6.getText().contains(" ") || jTextField6.getText().equals("")){
       jTextField6.requestFocus();
       JOptionPane.showMessageDialog( null, "Pesquise uma Matrícula! ","Aviso",JOptionPane.WARNING_MESSAGE); 
       return;
      } 
        jButton3.setBackground(Color.RED);  
        try{ //tratamento de erros
      Class.forName("com.mysql.jdbc.Driver");//busca Driver
      //conecta no BD
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cf0","root","fss3");
      Statement stmt= con.createStatement();//objeto comdo sql
String excMatricula= jTextField6.getText();
           int registro=stmt.executeUpdate("delete from cf3 where Matricula=" + excMatricula); 
if (registro!=0) JOptionPane.showMessageDialog(this,"Dados Excluidos!");
            else JOptionPane.showMessageDialog(this,"Dados não Excluidos!");
        stmt.close();
jTextField1.setText("");
jTextField2.setText("");
jTextField3.setText("");
jFormattedTextField1.setText("");
jTextField4.setText("");
jTextField5.setText("");
jTextArea1.setText("");
jLabel3.setIcon(null);

//Limpa a caixa de texto
        con.close(); //fecha conexão com BD
      } catch(SQLException e){ //trata os erros
            JOptionPane.showMessageDialog(this,"Erro Cmdo SQL "+e.getMessage());
            } catch(ClassNotFoundException e){       
             JOptionPane.showMessageDialog(this,"Driver não encontrado");
        }


    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:

        if(jTextField7.getText().equals("")){
       jTextField7.requestFocus();
       JOptionPane.showMessageDialog( null, "Pesquise um Nome! ","Aviso",JOptionPane.WARNING_MESSAGE); 
       return;
      } 
        jButton13.setBackground(Color.GREEN);  
        boolean pesquisa=true;
    try{ //tratamento de erros

            

            // Localiza o driver  utilizado

            Class.forName("com.mysql.jdbc.Driver");

            //  Conectar no banco, que no meu caso é o eletiva na porta 3306 a padrão.

            String url = "jdbc:mysql://localhost/cf0";

            Connection con = DriverManager.getConnection(url, "root", "fss3");

            

            //objeto comdo sql

            Statement stmt = con.createStatement();

            

            // As variaveis a,b e c recebendo os dados digitados nos campos nome,endereco e sexo.
     
    String ConsNome = jTextField7.getText();

          // Comando para a pesquisa de dados

            ResultSet RS  =stmt.executeQuery("Select * from  cf3 where  nome='"+ ConsNome+ "' "); 

        

       // Comando para exibir todos os dados do cliente.   

while (RS.next()){

  

     int Mat= RS.getInt("Matricula");//Pega a Matricula
                jTextField1.setText(String.valueOf(Mat)); //converte Inteiro para String.
                jTextField2.setText(RS.getString("Nome")); // Pega o Nome
                 jTextField3.setText(RS.getString("Endereco")); 
                jFormattedTextField1.setText(RS.getString("Telefone"));
                 jTextField4.setText(RS.getString("RG")); 
                  jTextField5.setText(RS.getString("CPF")); 
                   jTextArea1.setText(RS.getString("Observacao")); 
               ByteArrayOutputStream ouput=new ByteArrayOutputStream();
InputStream datos= RS.getBinaryStream("Foto");
int ten=datos.read();
while (ten>=0) {
ouput.write ((char) ten);
ten=datos.read();

}
Image image=Toolkit.getDefaultToolkit().createImage(ouput.toByteArray());
image=image.getScaledInstance(150, 150, 1);
jLabel3.setIcon(new ImageIcon(image));

     pesquisa = false;

             }
 // Caso os dados do cliente não for localizado exibe uma mensagem.

           if( pesquisa){ JOptionPane.showMessageDialog(this,"Dados Não Encontrados!"); }           

            

            RS.close();

            con.close();  // fecha conexão do banco de dados.

            

            //Tratamentos dos erros.

            

        }  catch( Exception e){

            JOptionPane.showMessageDialog(this,  "Erro  Cmdo  SQL  " + e.getMessage() );

            

        }    
    
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
     jButton7.setBackground(Color.RED); 
        try{ //tratamento de erros
         conecta.executaSQL("Select Foto,Matricula,Nome,Endereco,Telefone,RG,CPF,Observacao from cf3 where Matricula=" + jTextField6.getText() );
         JRResultSetDataSource relatResul = new  JRResultSetDataSource(conecta.rs);
          JasperPrint jp = JasperFillManager.fillReport("C:\\Users\\Francimar\\Documents\\NetBeansProjects\\JavaAplicacao\\src\\Apli1\\report0.jasper", new HashMap(), relatResul);  
  JasperViewer jv = new JasperViewer(jp, false);  
      jv.setVisible(true);
  
  } catch (JRException ex) {
 JOptionPane.showMessageDialog(rootPane, " Erro ao chmar relatorio \nErro: " + ex );  
}
    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
   FrameGrabbingControl fgc = (FrameGrabbingControl) player.getControl("javax.media.control.FrameGrabbingControl");
        Buffer buffer = fgc.grabFrame();
        BufferToImage bti =  new BufferToImage((VideoFormat) buffer.getFormat());
        Image image = bti.createImage(buffer);
        JIResizeImage resize  = new JIResizeImage();
        bi = (BufferedImage) image;
        Image imageresize = resize.rescale(bi, 150,150);
        this.setImageButton(tbCamera, imageresize);
     
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        FileDialog fd = new FileDialog(Apli0.this, "Save Image", FileDialog.SAVE);
        fd.show();
        if (fd.getFile() !=null)
        {
            nfile = fd.getDirectory() + fd.getFile() + ".jpg";
            try{
                File make = new File(nfile);
                try{
                    ImageIO.write(bi, "jpg", make);

                }
                catch(IOException ex)
                {
                    Logger.getLogger(Apli0.class.getName()).log(Level.SEVERE,null,ex);

                }

            }
            catch(Exception ex)
            {
            }
        }
       





    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        if(jTextField6.getText().equals("")){
       jTextField6.requestFocus();
       JOptionPane.showMessageDialog( null, "Pesquise uma Matrícula ! ","Aviso",JOptionPane.WARNING_MESSAGE); 
       return;
      }   
        jButton11.setBackground(Color.YELLOW);  
        try {
    Class.forName("com.mysql.jdbc.Driver");//Driver JDBC – Fonte de Dados ODBC
    Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cf0","root","fss3");
    String update = "update cf3 set Foto=? where Matricula='" + 
        jTextField6.getText() + "'";
           PreparedStatement ps = con.prepareStatement(update);
    ps.setBinaryStream(1, fis,longitudBytes);
    ps.execute();  
     JOptionPane.showMessageDialog(null, "Imagem Alterada");
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, e);
}


    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
   player.close();
        player.deallocate();
     
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
     jButton14.setBackground(Color.RED); 
        if(jTextField8.getText().contains(" ") || jTextField8.getText().equals("")){
       jTextField8.requestFocus();
       JOptionPane.showMessageDialog( null, "Preencha os espaços da Página! ","Aviso",JOptionPane.WARNING_MESSAGE); 
       return;
      }
   try{ //tratamento de erros
         Class.forName("com.mysql.jdbc.Driver");//Driver JDBC – Fonte de Dados ODBC
         String sql = "insert into cf5 (Codigo,Nome,Endereco,Telefone,Rg,CPF,Produto,Valor,Desconto,Total,Observacao) values (?,?,?,?,?,?,?,?,?,?,?)";            
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost/cf0","root","fss3");
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setInt(1, Integer.parseInt(jTextField8.getText()));
       ps.setString(2, jTextField9.getText());
           
        ps.setString(3, jTextField10.getText());
        ps.setString(4, jFormattedTextField2.getText());
        ps.setString(5, jTextField11.getText());  
        ps.setString(6, jTextField12.getText());
         ps.setString(7, jTextField13.getText());
          ps.setString(8, jTextField14.getText());
           ps.setString(9, jTextField15.getText());
            ps.setString(10, jTextField16.getText());
        ps.setString(11, jTextArea2.getText());
       
        JOptionPane.showMessageDialog( this, " Dados Salvos! ");
        ps.execute();
        ps.close();
        con.close();  // fecha conexão com BD
       
        jTextField8.setText("");
        jTextField9.setText("");
        jTextField10.setText("");
        jFormattedTextField2.setText("");
        jTextField11.setText("");
        jTextField12.setText("");
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField15.setText("");
        jTextField16.setText("");
        jTextArea2.setText("");
      }  catch( SQLException e){ //trata os erros SQL
            JOptionPane.showMessageDialog(this, "Erro Cmdo SQL " + e.getMessage() );
            } catch( ClassNotFoundException e){      //trata erros de conexão
             JOptionPane.showMessageDialog( this, " Driver não encontrado " );
            }  
    
    
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
     jButton19.setBackground(Color.GREEN); 
        if(jTextField17.getText().contains(" ") || jTextField17.getText().equals("")){
       jTextField17.requestFocus();
       JOptionPane.showMessageDialog( null, "Pesquise um Código! ","Aviso",JOptionPane.WARNING_MESSAGE); 
       return;
      }    
     boolean consulta=true;  
           
         
          try{ 
            //tratamento de erros
           
           
            //conecta no BD
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cf0","root","fss3");
            Statement stmt= con.createStatement();//objeto comdo sql
           
            ResultSet RS= stmt.executeQuery("Select codigo,nome,endereco,telefone,rg,cpf,produto,valor,desconto,total,observacao from cf5 where Codigo=" + jTextField17.getText() );
             while (RS.next()){
             
             
             String Codigo; 
             String Nome;
             String Endereco; 
             String Telefone;
             String RG;
             String CPF;
             String Produto;
             String Valor;
             String Desconto;
             String Total;
             String Observacao; 
           
            Codigo = RS.getString(1);
            Nome = RS.getString(2);
            Endereco = RS.getString(3);
            Telefone = RS.getString(4);
            RG = RS.getString(5);
            CPF = RS.getString(6);
            Produto = RS.getString(7);
            Valor = RS.getString(8);
            Desconto = RS.getString(9);
            Total = RS.getString(10);
            Observacao = RS.getString(11);
            
             jTextField8.setText(Codigo);
             jTextField9.setText(Nome);
             jTextField10.setText(Endereco);
             jFormattedTextField2.setText(Telefone);
             jTextField11.setText(RG);
             jTextField12.setText(CPF);
             jTextField13.setText(Produto);
             jTextField14.setText(Valor);
             jTextField15.setText(Desconto);
             jTextField16.setText(Total);
             jTextArea2.setText(Observacao);
              consulta=false;
                
             }
            if (consulta) JOptionPane.showMessageDialog(this,"Dados Não Encontrados!");
              
            }  catch( SQLException e){ //trata os erros SQL
            JOptionPane.showMessageDialog(this, "Erro Cmdo SQL " + e.getMessage() ); 
            }
        
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
     jButton15.setBackground(Color.RED); 
        if(jTextField17.getText().contains(" ") || jTextField17.getText().equals("")){
       jTextField17.requestFocus();
       JOptionPane.showMessageDialog( null, "Pesquise um Código! ","Aviso",JOptionPane.WARNING_MESSAGE); 
       return;
      }    
     try{ //tratamento de erros
      Class.forName("com.mysql.jdbc.Driver");//busca Driver
      //conecta no BD
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cf0","root","fss3");
      Statement stmt= con.createStatement();//objeto comdo sql
String consCodigo= jTextField17.getText();
String cadCod=jTextField8.getText();
String cadNome=jTextField9.getText();
String cadEnd=jTextField10.getText();
String cadTel=jFormattedTextField2.getText();
String cadRG=jTextField11.getText();
String cadCPF=jTextField12.getText();
String cadPro=jTextField13.getText();
String cadVal=jTextField14.getText();
String cadDes=jTextField15.getText();
String cadTol=jTextField16.getText();
String cadObs=jTextArea2.getText();

int registro = stmt.executeUpdate("update cf5 set Nome='" + cadNome + "', Codigo='" + cadCod + "',  Endereco='" + cadEnd + "', telefone='" + cadTel + "', RG='" + cadRG + "', CPF='" + cadCPF + "',Produto='" + cadPro + "',Valor='" + cadVal + "',Desconto='" + cadDes + "',Total='" + cadTol + "', Observacao='" + cadObs + "' where Codigo=" + consCodigo);   
if (registro!=0) JOptionPane.showMessageDialog(this,"Dados Alterados!");
                 else JOptionPane.showMessageDialog(this,"Dados Não Alterados!");
            stmt.close();
            con.close(); //fecha conexão com BD
      } catch(SQLException e){ //trata os erros
            JOptionPane.showMessageDialog(this,"Erro Cmdo SQL "+e.getMessage());
            } catch(ClassNotFoundException e){       
             JOptionPane.showMessageDialog(this,"Driver não encontrado");
        }    
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    jButton17.setBackground(Color.RED);  
        jTextField8.setText("");
jTextField9.setText("");
jTextField10.setText("");
jFormattedTextField2.setText("");
jTextField11.setText("");
jTextField12.setText("");
  jTextField13.setText("");
    jTextField14.setText("");
      jTextField15.setText("");
        jTextField16.setText("");
jTextArea2.setText("");
  
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
  if(jTextField17.getText().contains(" ") || jTextField17.getText().equals("")){
       jTextField17.requestFocus();
       JOptionPane.showMessageDialog( null, "Pesquise um Código! ","Aviso",JOptionPane.WARNING_MESSAGE); 
       return;
      } 
        jButton16.setBackground(Color.RED);  
        try{ //tratamento de erros
      Class.forName("com.mysql.jdbc.Driver");//busca Driver
      //conecta no BD
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cf0","root","fss3");
      Statement stmt= con.createStatement();//objeto comdo sql
String excCodigo= jTextField17.getText();
           int registro=stmt.executeUpdate("delete from cf5 where Codigo=" + excCodigo); 
if (registro!=0) JOptionPane.showMessageDialog(this,"Dados Excluidos!");
            else JOptionPane.showMessageDialog(this,"Dados não Excluidos!");
        stmt.close();
jTextField8.setText("");
jTextField9.setText("");
jTextField10.setText("");
jFormattedTextField2.setText("");
jTextField11.setText("");
jTextField12.setText("");
jTextField13.setText("");
jTextField14.setText("");
jTextField15.setText("");
jTextField16.setText("");
jTextArea2.setText("");


//Limpa a caixa de texto
        con.close(); //fecha conexão com BD
      } catch(SQLException e){ //trata os erros
            JOptionPane.showMessageDialog(this,"Erro Cmdo SQL "+e.getMessage());
            } catch(ClassNotFoundException e){       
             JOptionPane.showMessageDialog(this,"Driver não encontrado");
        }

       
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
  if(jTextField18.getText().equals("")){
       jTextField18.requestFocus();
       JOptionPane.showMessageDialog( null, "Pesquise um Nome! ","Aviso",JOptionPane.WARNING_MESSAGE); 
       return;
      } 
        jButton20.setBackground(Color.GREEN);  
        boolean pesquisa=true;
    try{ //tratamento de erros

            

            // Localiza o driver  utilizado

            Class.forName("com.mysql.jdbc.Driver");

            //  Conectar no banco, que no meu caso é o eletiva na porta 3306 a padrão.

            String url = "jdbc:mysql://localhost/cf0";

            Connection con = DriverManager.getConnection(url, "root", "fss3");

            

            //objeto comdo sql

            Statement stmt = con.createStatement();

            

            // As variaveis a,b e c recebendo os dados digitados nos campos nome,endereco e sexo.
     
    String ConsNome = jTextField18.getText();

          // Comando para a pesquisa de dados

            ResultSet RS  =stmt.executeQuery("Select * from  cf5 where  nome='"+ ConsNome+ "' "); 

        

       // Comando para exibir todos os dados do cliente.   

while (RS.next()){

  

     int Cod= RS.getInt("Codigo");//Pega a Matricula
                jTextField8.setText(String.valueOf(Cod)); //converte Inteiro para String.
                jTextField9.setText(RS.getString("Nome")); // Pega o Nome
                 jTextField10.setText(RS.getString("Endereco")); 
                jFormattedTextField2.setText(RS.getString("Telefone"));
                 jTextField11.setText(RS.getString("RG")); 
                  jTextField12.setText(RS.getString("CPF")); 
                  jTextField13.setText(RS.getString("Produto"));
                  jTextField14.setText(RS.getString("Valor"));
                  jTextField15.setText(RS.getString("Desconto"));
                  jTextField16.setText(RS.getString("Total")); 
                   jTextArea2.setText(RS.getString("Observacao")); 
              

     pesquisa = false;

             }
 // Caso os dados do cliente não for localizado exibe uma mensagem.

           if( pesquisa){ JOptionPane.showMessageDialog(this,"Dados Não Encontrados!"); }           

            

            RS.close();

            con.close();  // fecha conexão do banco de dados.

            

            //Tratamentos dos erros.

            

        }  catch( Exception e){

            JOptionPane.showMessageDialog(this,  "Erro  Cmdo  SQL  " + e.getMessage() );

            

        }    
           
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
     jButton18.setBackground(Color.RED); 
        try{ //tratamento de erros
         conecta.executaSQL("Select Codigo,Nome,Endereco,Telefone,RG,CPF,Produto,Valor,Desconto,Total,Observacao from cf5 where Codigo=" + jTextField17.getText() );
         JRResultSetDataSource relatResul = new  JRResultSetDataSource(conecta.rs);
          JasperPrint jp = JasperFillManager.fillReport("C:\\Users\\Francimar\\Documents\\NetBeansProjects\\JavaAplicacao\\src\\Apli1\\report1.jasper", new HashMap(), relatResul);  
  JasperViewer jv = new JasperViewer(jp, false);  
      jv.setVisible(true);
  
  } catch (JRException ex) {
 JOptionPane.showMessageDialog(rootPane, " Erro ao chmar relatorio \nErro: " + ex );  
}    
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
   jButton21.setBackground(Color.RED); 
        try{ //tratamento de erros
       Class.forName("com.mysql.jdbc.Driver");//busca Driver
//conecta no BD
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost/cf0","root","fss3");
       Statement stmt =
con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
       RS= stmt.executeQuery("Select * from cf5");
       } catch(SQLException e){ //trata os erros
            JOptionPane.showMessageDialog(this,"Erro Cmdo SQL " + e.getMessage());
       } catch(ClassNotFoundException e){     
           JOptionPane.showMessageDialog(this,"Driver não encontrado");
       }


     
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
     jButton22.setBackground(Color.RED); 
        try{
    RS.first();
    jTextField8.setText(RS.getString("Codigo"));
    jTextField9.setText(RS.getString("Nome"));
     jTextField10.setText(RS.getString("Endereco"));
     jFormattedTextField2.setText(RS.getString("Telefone"));
     jTextField11.setText(RS.getString("RG"));
     jTextField12.setText(RS.getString("Cpf"));
     jTextField13.setText(RS.getString("Produto"));
     jTextField14.setText(RS.getString("Valor"));
     jTextField15.setText(RS.getString("Desconto"));
     jTextField16.setText(RS.getString("Total"));
     jTextArea2.setText(RS.getString("Observacao"));
 } catch(SQLException e){ //trata os erros
    JOptionPane.showMessageDialog(this,"Não Existem mais Registros");        
}
   
    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        jButton23.setBackground(Color.RED); 
        try{
    RS.previous();
    jTextField8.setText(RS.getString("Codigo"));
    jTextField9.setText(RS.getString("Nome"));
     jTextField10.setText(RS.getString("Endereco"));
     jFormattedTextField2.setText(RS.getString("Telefone"));
     jTextField11.setText(RS.getString("RG"));
     jTextField12.setText(RS.getString("Cpf"));
     jTextField13.setText(RS.getString("Produto"));
     jTextField14.setText(RS.getString("Valor"));
     jTextField15.setText(RS.getString("Desconto"));
     jTextField16.setText(RS.getString("Total"));
     jTextArea2.setText(RS.getString("Observacao"));
 } catch(SQLException e){ //trata os erros
    JOptionPane.showMessageDialog(this,"Primeiro Código");        
}
   
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
     jButton24.setBackground(Color.RED); 
        try{
    RS.next();
    jTextField8.setText(RS.getString("Codigo"));
    jTextField9.setText(RS.getString("Nome"));
     jTextField10.setText(RS.getString("Endereco"));
     jFormattedTextField2.setText(RS.getString("Telefone"));
     jTextField11.setText(RS.getString("RG"));
     jTextField12.setText(RS.getString("Cpf"));
     jTextField13.setText(RS.getString("Produto"));
     jTextField14.setText(RS.getString("Valor"));
     jTextField15.setText(RS.getString("Desconto"));
     jTextField16.setText(RS.getString("Total"));
     jTextArea2.setText(RS.getString("Observacao"));
 } catch(SQLException e){ //trata os erros
    JOptionPane.showMessageDialog(this,"Não Existem mais Registros");        
}
      
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25ActionPerformed
        // TODO add your handling code here:
     jButton25.setBackground(Color.RED); 
        try{
    RS.last();
    jTextField8.setText(RS.getString("Codigo"));
    jTextField9.setText(RS.getString("Nome"));
     jTextField10.setText(RS.getString("Endereco"));
     jFormattedTextField2.setText(RS.getString("Telefone"));
     jTextField11.setText(RS.getString("RG"));
     jTextField12.setText(RS.getString("Cpf"));
     jTextField13.setText(RS.getString("Produto"));
     jTextField14.setText(RS.getString("Valor"));
     jTextField15.setText(RS.getString("Desconto"));
     jTextField16.setText(RS.getString("Total"));
     jTextArea2.setText(RS.getString("Observacao"));
 } catch(SQLException e){ //trata os erros
    JOptionPane.showMessageDialog(this,"Último  Código");        
}
      
    }//GEN-LAST:event_jButton25ActionPerformed

    private void tbCameraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbCameraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbCameraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apli0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apli0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apli0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apli0.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apli0().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<Apli1.Cf3> cf3List;
    private javax.persistence.Query cf3Query;
    private java.util.List<Apli1.Cf5> cf5List;
    private javax.persistence.Query cf5Query;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton tbCamera;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
